version: '3.8'

services:
  reader:
    build: .
    environment:
      - PYTHONUNBUFFERED=1  # Для вывода логов в реальном времени
    volumes:
      - .:/app  # Для горячей перезагрузки кода (опционально)
    logging:
      driver: "json-file"  # Драйвер логирования (по умолчанию)
      options:
        max-size: "10m"    # Максимальный размер одного лог-файла (10 мегабайт)
        max-file: "3"      # Максимальное количество лог-файлов (старые будут удаляться)